version: "3.8"

services:
  db:
    image: postgres:17
    ports:
      - "1235:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
